# Generated by Django 6.0.3 on 2026-05-01 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joatham_messages', '0003_publicquestion_reply_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='conversation',
            new_name='joatham_mes_entrepr_ecc96e_idx',
            old_name='joatham_mes_entrepr_705580_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='joatham_mes_entrepr_08e680_idx',
            old_name='joatham_mes_entrepr_f3ae1f_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='joatham_mes_convers_03a88c_idx',
            old_name='joatham_mes_convers_970345_idx',
        ),
        migrations.RenameIndex(
            model_name='publicquestion',
            new_name='joatham_mes_statut_dc3ec8_idx',
            old_name='joatham_mes_statut_169e93_idx',
        ),
        migrations.RenameIndex(
            model_name='publicquestion',
            new_name='joatham_mes_email_af9257_idx',
            old_name='joatham_mes_email_9ac2b5_idx',
        ),
        migrations.RenameIndex(
            model_name='suggestionsuperadmin',
            new_name='joatham_mes_statut_f5d771_idx',
            old_name='joatham_mes_statut_e59101_idx',
        ),
        migrations.RenameIndex(
            model_name='suggestionsuperadmin',
            new_name='joatham_mes_entrepr_a91391_idx',
            old_name='joatham_mes_entrepr_8d4d96_idx',
        ),
    ]
