# Generated by Codex on 2026-05-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("joatham_messages", "0004_rename_joatham_mes_entrepr_705580_idx_joatham_mes_entrepr_ecc96e_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicquestion",
            name="is_lead",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="publicquestion",
            name="lead_status",
            field=models.CharField(
                choices=[
                    ("nouveau", "Nouveau"),
                    ("en_cours", "En cours"),
                    ("converti", "Converti"),
                ],
                default="nouveau",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="publicquestion",
            name="source",
            field=models.CharField(default="question_publique", max_length=50),
        ),
    ]
