# Generated by Codex on 2026-05-02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("joatham_users", "0017_entrepriseinvitation"),
        ("joatham_messages", "0005_publicquestion_lead_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicquestion",
            name="invitation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="public_questions",
                to="joatham_users.entrepriseinvitation",
            ),
        ),
    ]
