# Generated by Django 6.0.3 on 2026-04-19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("joatham_users", "0005_user_role_proprietaire"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(max_length=100)),
                ("module", models.CharField(max_length=50)),
                ("objet_type", models.CharField(blank=True, default="", max_length=100)),
                ("objet_id", models.PositiveIntegerField(blank=True, null=True)),
                ("description", models.CharField(max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="joatham_users.entreprise",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to="joatham_users.user",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_creation", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(fields=["entreprise", "module", "date_creation"], name="core_activi_entrepr_2d4880_idx"),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(fields=["entreprise", "action", "date_creation"], name="core_activi_entrepr_7a617e_idx"),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(fields=["entreprise", "utilisateur", "date_creation"], name="core_activi_entrepr_59bb95_idx"),
        ),
    ]
