# Generated by Django 6.0.3 on 2026-04-19 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_activitylog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='core_activi_entrepr_dceb63_idx',
            old_name='core_activi_entrepr_2d4880_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='core_activi_entrepr_f2658a_idx',
            old_name='core_activi_entrepr_7a617e_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='core_activi_entrepr_96689e_idx',
            old_name='core_activi_entrepr_59bb95_idx',
        ),
    ]
