# Generated by Django 6.0.3 on 2026-04-23 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_core_activi_entrepr_2d4880_idx_core_activi_entrepr_dceb63_idx_and_more'),
        ('joatham_users', '0013_user_email_verified_user_email_verified_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duree', models.CharField(choices=[('mensuel', 'Mensuel'), ('trimestriel', 'Trimestriel'), ('annuel', 'Annuel')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Valide'), ('refuse', 'Refuse')], default='en_attente', max_length=20)),
                ('reference_paiement', models.CharField(max_length=120)),
                ('preuve_paiement', models.FileField(blank=True, null=True, upload_to='abonnements/preuves/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_abonnement', to='joatham_users.entreprise')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements_abonnement', to='joatham_users.abonnement')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_abonnement_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation', '-id'],
                'indexes': [models.Index(fields=['entreprise', 'statut', 'date_creation'], name='core_paieme_entrepr_96e0e2_idx'), models.Index(fields=['statut', 'date_creation'], name='core_paieme_statut_48229e_idx')],
            },
        ),
    ]
