# Generated by Django 6.0.3 on 2026-04-26 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_exchange_rates_platform_settings'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='exchangerate',
            new_name='core_exchan_devise__cb06c8_idx',
            old_name='core_exchan_devise__e3cf1a_idx',
        ),
    ]
