WORLD_COUNTRIES = [
    ("AF", "Afghanistan", "AFN"),
    ("ZA", "Afrique du Sud", "ZAR"),
    ("AL", "Albanie", "ALL"),
    ("DZ", "Algerie", "DZD"),
    ("DE", "Allemagne", "EUR"),
    ("AD", "Andorre", "EUR"),
    ("AO", "Angola", "AOA"),
    ("AG", "Antigua-et-Barbuda", "XCD"),
    ("SA", "Arabie saoudite", "SAR"),
    ("AR", "Argentine", "ARS"),
    ("AM", "Armenie", "AMD"),
    ("AU", "Australie", "AUD"),
    ("AT", "Autriche", "EUR"),
    ("AZ", "Azerbaidjan", "AZN"),
    ("BS", "Bahamas", "BSD"),
    ("BH", "Bahrein", "BHD"),
    ("BD", "Bangladesh", "BDT"),
    ("BB", "Barbade", "BBD"),
    ("BE", "Belgique", "EUR"),
    ("BZ", "Belize", "BZD"),
    ("BJ", "Benin", "XOF"),
    ("BT", "Bhoutan", "BTN"),
    ("BY", "Bielorussie", "BYN"),
    ("MM", "Birmanie", "MMK"),
    ("BO", "Bolivie", "BOB"),
    ("BA", "Bosnie-Herzegovine", "BAM"),
    ("BW", "Botswana", "BWP"),
    ("BR", "Bresil", "BRL"),
    ("BN", "Brunei", "BND"),
    ("BG", "Bulgarie", "BGN"),
    ("BF", "Burkina Faso", "XOF"),
    ("BI", "Burundi", "BIF"),
    ("CV", "Cap-Vert", "CVE"),
    ("KH", "Cambodge", "KHR"),
    ("CM", "Cameroun", "XAF"),
    ("CA", "Canada", "CAD"),
    ("CF", "Centrafrique", "XAF"),
    ("CL", "Chili", "CLP"),
    ("CN", "Chine", "CNY"),
    ("CY", "Chypre", "EUR"),
    ("CO", "Colombie", "COP"),
    ("KM", "Comores", "KMF"),
    ("CG", "Congo-Brazzaville", "XAF"),
    ("CD", "RDC", "CDF"),
    ("KP", "Coree du Nord", "KPW"),
    ("KR", "Coree du Sud", "KRW"),
    ("CR", "Costa Rica", "CRC"),
    ("CI", "Cote d'Ivoire", "XOF"),
    ("HR", "Croatie", "EUR"),
    ("CU", "Cuba", "CUP"),
    ("DK", "Danemark", "DKK"),
    ("DJ", "Djibouti", "DJF"),
    ("DM", "Dominique", "XCD"),
    ("EG", "Egypte", "EGP"),
    ("AE", "Emirats arabes unis", "AED"),
    ("EC", "Equateur", "USD"),
    ("ER", "Erythree", "ERN"),
    ("ES", "Espagne", "EUR"),
    ("EE", "Estonie", "EUR"),
    ("SZ", "Eswatini", "SZL"),
    ("US", "Etats-Unis", "USD"),
    ("ET", "Ethiopie", "ETB"),
    ("FJ", "Fidji", "FJD"),
    ("FI", "Finlande", "EUR"),
    ("FR", "France", "EUR"),
    ("GA", "Gabon", "XAF"),
    ("GM", "Gambie", "GMD"),
    ("GE", "Georgie", "GEL"),
    ("GH", "Ghana", "GHS"),
    ("GR", "Grece", "EUR"),
    ("GD", "Grenade", "XCD"),
    ("GT", "Guatemala", "GTQ"),
    ("GN", "Guinee", "GNF"),
    ("GQ", "Guinee equatoriale", "XAF"),
    ("GW", "Guinee-Bissau", "XOF"),
    ("GY", "Guyana", "GYD"),
    ("HT", "Haiti", "HTG"),
    ("HN", "Honduras", "HNL"),
    ("HU", "Hongrie", "HUF"),
    ("IN", "Inde", "INR"),
    ("ID", "Indonesie", "IDR"),
    ("IQ", "Irak", "IQD"),
    ("IR", "Iran", "IRR"),
    ("IE", "Irlande", "EUR"),
    ("IS", "Islande", "ISK"),
    ("IL", "Israel", "ILS"),
    ("IT", "Italie", "EUR"),
    ("JM", "Jamaique", "JMD"),
    ("JP", "Japon", "JPY"),
    ("JO", "Jordanie", "JOD"),
    ("KZ", "Kazakhstan", "KZT"),
    ("KE", "Kenya", "KES"),
    ("KG", "Kirghizistan", "KGS"),
    ("KI", "Kiribati", "AUD"),
    ("KW", "Koweit", "KWD"),
    ("LA", "Laos", "LAK"),
    ("LS", "Lesotho", "LSL"),
    ("LV", "Lettonie", "EUR"),
    ("LB", "Liban", "LBP"),
    ("LR", "Liberia", "LRD"),
    ("LY", "Libye", "LYD"),
    ("LI", "Liechtenstein", "CHF"),
    ("LT", "Lituanie", "EUR"),
    ("LU", "Luxembourg", "EUR"),
    ("MK", "Macedoine du Nord", "MKD"),
    ("MG", "Madagascar", "MGA"),
    ("MY", "Malaisie", "MYR"),
    ("MW", "Malawi", "MWK"),
    ("MV", "Maldives", "MVR"),
    ("ML", "Mali", "XOF"),
    ("MT", "Malte", "EUR"),
    ("MA", "Maroc", "MAD"),
    ("MH", "Marshall", "USD"),
    ("MU", "Maurice", "MUR"),
    ("MR", "Mauritanie", "MRU"),
    ("MX", "Mexique", "MXN"),
    ("FM", "Micronesie", "USD"),
    ("MD", "Moldavie", "MDL"),
    ("MC", "Monaco", "EUR"),
    ("MN", "Mongolie", "MNT"),
    ("ME", "Montenegro", "EUR"),
    ("MZ", "Mozambique", "MZN"),
    ("NA", "Namibie", "NAD"),
    ("NR", "Nauru", "AUD"),
    ("NP", "Nepal", "NPR"),
    ("NI", "Nicaragua", "NIO"),
    ("NE", "Niger", "XOF"),
    ("NG", "Nigeria", "NGN"),
    ("NO", "Norvege", "NOK"),
    ("NZ", "Nouvelle-Zelande", "NZD"),
    ("OM", "Oman", "OMR"),
    ("UG", "Ouganda", "UGX"),
    ("UZ", "Ouzbekistan", "UZS"),
    ("PK", "Pakistan", "PKR"),
    ("PW", "Palaos", "USD"),
    ("PA", "Panama", "PAB"),
    ("PG", "Papouasie-Nouvelle-Guinee", "PGK"),
    ("PY", "Paraguay", "PYG"),
    ("NL", "Pays-Bas", "EUR"),
    ("PE", "Perou", "PEN"),
    ("PH", "Philippines", "PHP"),
    ("PL", "Pologne", "PLN"),
    ("PT", "Portugal", "EUR"),
    ("QA", "Qatar", "QAR"),
    ("RO", "Roumanie", "RON"),
    ("GB", "Royaume-Uni", "GBP"),
    ("RU", "Russie", "RUB"),
    ("RW", "Rwanda", "RWF"),
    ("KN", "Saint-Christophe-et-Nieves", "XCD"),
    ("SM", "Saint-Marin", "EUR"),
    ("VC", "Saint-Vincent-et-les-Grenadines", "XCD"),
    ("LC", "Sainte-Lucie", "XCD"),
    ("SB", "Salomon", "SBD"),
    ("SV", "Salvador", "USD"),
    ("WS", "Samoa", "WST"),
    ("ST", "Sao Tome-et-Principe", "STN"),
    ("SN", "Senegal", "XOF"),
    ("RS", "Serbie", "RSD"),
    ("SC", "Seychelles", "SCR"),
    ("SL", "Sierra Leone", "SLE"),
    ("SG", "Singapour", "SGD"),
    ("SK", "Slovaquie", "EUR"),
    ("SI", "Slovenie", "EUR"),
    ("SO", "Somalie", "SOS"),
    ("SD", "Soudan", "SDG"),
    ("SS", "Soudan du Sud", "SSP"),
    ("LK", "Sri Lanka", "LKR"),
    ("SE", "Suede", "SEK"),
    ("CH", "Suisse", "CHF"),
    ("SR", "Suriname", "SRD"),
    ("SY", "Syrie", "SYP"),
    ("TJ", "Tadjikistan", "TJS"),
    ("TZ", "Tanzanie", "TZS"),
    ("TD", "Tchad", "XAF"),
    ("CZ", "Tchequie", "CZK"),
    ("TH", "Thailande", "THB"),
    ("TL", "Timor oriental", "USD"),
    ("TG", "Togo", "XOF"),
    ("TO", "Tonga", "TOP"),
    ("TT", "Trinite-et-Tobago", "TTD"),
    ("TN", "Tunisie", "TND"),
    ("TM", "Turkmenistan", "TMT"),
    ("TR", "Turquie", "TRY"),
    ("TV", "Tuvalu", "AUD"),
    ("UA", "Ukraine", "UAH"),
    ("UY", "Uruguay", "UYU"),
    ("VU", "Vanuatu", "VUV"),
    ("VA", "Vatican", "EUR"),
    ("VE", "Venezuela", "VES"),
    ("VN", "Vietnam", "VND"),
    ("YE", "Yemen", "YER"),
    ("ZM", "Zambie", "ZMW"),
    ("ZW", "Zimbabwe", "ZWG"),
]


CURRENCY_DETAILS = {
    "AED": {"name": "Dirham des Emirats arabes unis", "symbol": "AED"},
    "AFN": {"name": "Afghani", "symbol": "AFN"},
    "ALL": {"name": "Lek albanais", "symbol": "ALL"},
    "AMD": {"name": "Dram armenien", "symbol": "AMD"},
    "AOA": {"name": "Kwanza angolais", "symbol": "Kz"},
    "ARS": {"name": "Peso argentin", "symbol": "ARS"},
    "AUD": {"name": "Dollar australien", "symbol": "A$"},
    "AZN": {"name": "Manat azerbaidjanais", "symbol": "AZN"},
    "BAM": {"name": "Mark convertible", "symbol": "BAM"},
    "BBD": {"name": "Dollar barbadien", "symbol": "BBD"},
    "BDT": {"name": "Taka bangladais", "symbol": "BDT"},
    "BGN": {"name": "Lev bulgare", "symbol": "BGN"},
    "BHD": {"name": "Dinar bahreini", "symbol": "BHD"},
    "BIF": {"name": "Franc burundais", "symbol": "BIF"},
    "BND": {"name": "Dollar brunien", "symbol": "BND"},
    "BOB": {"name": "Boliviano", "symbol": "BOB"},
    "BRL": {"name": "Real bresilien", "symbol": "R$"},
    "BSD": {"name": "Dollar bahamien", "symbol": "BSD"},
    "BTN": {"name": "Ngultrum", "symbol": "BTN"},
    "BWP": {"name": "Pula", "symbol": "BWP"},
    "BYN": {"name": "Rouble bielorusse", "symbol": "BYN"},
    "BZD": {"name": "Dollar belizien", "symbol": "BZD"},
    "CAD": {"name": "Dollar canadien", "symbol": "CA$"},
    "CDF": {"name": "Franc congolais", "symbol": "FC"},
    "CHF": {"name": "Franc suisse", "symbol": "CHF"},
    "CLP": {"name": "Peso chilien", "symbol": "CLP"},
    "CNY": {"name": "Yuan chinois", "symbol": "CNY"},
    "COP": {"name": "Peso colombien", "symbol": "COP"},
    "CRC": {"name": "Colon costaricien", "symbol": "CRC"},
    "CUP": {"name": "Peso cubain", "symbol": "CUP"},
    "CVE": {"name": "Escudo cap-verdien", "symbol": "CVE"},
    "CZK": {"name": "Couronne tcheque", "symbol": "CZK"},
    "DJF": {"name": "Franc djiboutien", "symbol": "DJF"},
    "DKK": {"name": "Couronne danoise", "symbol": "DKK"},
    "DZD": {"name": "Dinar algerien", "symbol": "DZD"},
    "EGP": {"name": "Livre egyptienne", "symbol": "EGP"},
    "ERN": {"name": "Nakfa", "symbol": "ERN"},
    "ETB": {"name": "Birr ethiopien", "symbol": "ETB"},
    "EUR": {"name": "Euro", "symbol": "EUR"},
    "FJD": {"name": "Dollar fidjien", "symbol": "FJD"},
    "GBP": {"name": "Livre sterling", "symbol": "GBP"},
    "GEL": {"name": "Lari georgien", "symbol": "GEL"},
    "GHS": {"name": "Cedi ghanéen", "symbol": "GHS"},
    "GMD": {"name": "Dalasi gambien", "symbol": "GMD"},
    "GNF": {"name": "Franc guineen", "symbol": "GNF"},
    "GTQ": {"name": "Quetzal", "symbol": "GTQ"},
    "GYD": {"name": "Dollar guyanien", "symbol": "GYD"},
    "HNL": {"name": "Lempira", "symbol": "HNL"},
    "HTG": {"name": "Gourde haitienne", "symbol": "HTG"},
    "HUF": {"name": "Forint", "symbol": "HUF"},
    "IDR": {"name": "Roupie indonesienne", "symbol": "IDR"},
    "ILS": {"name": "Shekel israélien", "symbol": "ILS"},
    "INR": {"name": "Roupie indienne", "symbol": "INR"},
    "IQD": {"name": "Dinar irakien", "symbol": "IQD"},
    "IRR": {"name": "Rial iranien", "symbol": "IRR"},
    "ISK": {"name": "Couronne islandaise", "symbol": "ISK"},
    "JMD": {"name": "Dollar jamaicain", "symbol": "JMD"},
    "JOD": {"name": "Dinar jordanien", "symbol": "JOD"},
    "JPY": {"name": "Yen japonais", "symbol": "JPY"},
    "KES": {"name": "Shilling kenyan", "symbol": "KES"},
    "KGS": {"name": "Som kirghize", "symbol": "KGS"},
    "KHR": {"name": "Riel cambodgien", "symbol": "KHR"},
    "KMF": {"name": "Franc comorien", "symbol": "KMF"},
    "KPW": {"name": "Won nord-coreen", "symbol": "KPW"},
    "KRW": {"name": "Won sud-coreen", "symbol": "KRW"},
    "KWD": {"name": "Dinar koweitien", "symbol": "KWD"},
    "KZT": {"name": "Tenge kazakh", "symbol": "KZT"},
    "LAK": {"name": "Kip lao", "symbol": "LAK"},
    "LBP": {"name": "Livre libanaise", "symbol": "LBP"},
    "LKR": {"name": "Roupie sri-lankaise", "symbol": "LKR"},
    "LRD": {"name": "Dollar liberien", "symbol": "LRD"},
    "LSL": {"name": "Loti", "symbol": "LSL"},
    "LYD": {"name": "Dinar libyen", "symbol": "LYD"},
    "MAD": {"name": "Dirham marocain", "symbol": "MAD"},
    "MDL": {"name": "Leu moldave", "symbol": "MDL"},
    "MGA": {"name": "Ariary", "symbol": "MGA"},
    "MKD": {"name": "Denar macedonien", "symbol": "MKD"},
    "MMK": {"name": "Kyat", "symbol": "MMK"},
    "MNT": {"name": "Tugrik", "symbol": "MNT"},
    "MOP": {"name": "Pataca", "symbol": "MOP"},
    "MRU": {"name": "Ouguiya", "symbol": "MRU"},
    "MUR": {"name": "Roupie mauricienne", "symbol": "MUR"},
    "MVR": {"name": "Rufiyaa", "symbol": "MVR"},
    "MWK": {"name": "Kwacha malawite", "symbol": "MWK"},
    "MXN": {"name": "Peso mexicain", "symbol": "MX$"},
    "MYR": {"name": "Ringgit malaisien", "symbol": "MYR"},
    "MZN": {"name": "Metical mozambicain", "symbol": "MZN"},
    "NAD": {"name": "Dollar namibien", "symbol": "NAD"},
    "NGN": {"name": "Naira", "symbol": "NGN"},
    "NIO": {"name": "Cordoba", "symbol": "NIO"},
    "NOK": {"name": "Couronne norvegienne", "symbol": "NOK"},
    "NPR": {"name": "Roupie nepalaise", "symbol": "NPR"},
    "NZD": {"name": "Dollar neo-zelandais", "symbol": "NZ$"},
    "OMR": {"name": "Rial omanais", "symbol": "OMR"},
    "PAB": {"name": "Balboa", "symbol": "PAB"},
    "PEN": {"name": "Sol", "symbol": "PEN"},
    "PGK": {"name": "Kina", "symbol": "PGK"},
    "PHP": {"name": "Peso philippin", "symbol": "PHP"},
    "PKR": {"name": "Roupie pakistanaise", "symbol": "PKR"},
    "PLN": {"name": "Zloty", "symbol": "PLN"},
    "PYG": {"name": "Guarani", "symbol": "PYG"},
    "QAR": {"name": "Riyal qatari", "symbol": "QAR"},
    "RON": {"name": "Leu roumain", "symbol": "RON"},
    "RSD": {"name": "Dinar serbe", "symbol": "RSD"},
    "RUB": {"name": "Rouble russe", "symbol": "RUB"},
    "RWF": {"name": "Franc rwandais", "symbol": "RWF"},
    "SAR": {"name": "Riyal saoudien", "symbol": "SAR"},
    "SBD": {"name": "Dollar des Salomon", "symbol": "SBD"},
    "SCR": {"name": "Roupie seychelloise", "symbol": "SCR"},
    "SDG": {"name": "Livre soudanaise", "symbol": "SDG"},
    "SEK": {"name": "Couronne suedoise", "symbol": "SEK"},
    "SGD": {"name": "Dollar de Singapour", "symbol": "SGD"},
    "SLE": {"name": "Leone", "symbol": "SLE"},
    "SOS": {"name": "Shilling somalien", "symbol": "SOS"},
    "SRD": {"name": "Dollar surinamais", "symbol": "SRD"},
    "SSP": {"name": "Livre sud-soudanaise", "symbol": "SSP"},
    "STN": {"name": "Dobra", "symbol": "STN"},
    "SZL": {"name": "Lilangeni", "symbol": "SZL"},
    "SYP": {"name": "Livre syrienne", "symbol": "SYP"},
    "THB": {"name": "Baht", "symbol": "THB"},
    "TJS": {"name": "Somoni", "symbol": "TJS"},
    "TMT": {"name": "Manat turkmene", "symbol": "TMT"},
    "TND": {"name": "Dinar tunisien", "symbol": "TND"},
    "TOP": {"name": "Paanga", "symbol": "TOP"},
    "TRY": {"name": "Livre turque", "symbol": "TRY"},
    "TTD": {"name": "Dollar de Trinite-et-Tobago", "symbol": "TTD"},
    "TZS": {"name": "Shilling tanzanien", "symbol": "TZS"},
    "UAH": {"name": "Hryvnia", "symbol": "UAH"},
    "UGX": {"name": "Shilling ougandais", "symbol": "UGX"},
    "USD": {"name": "Dollar americain", "symbol": "$"},
    "UYU": {"name": "Peso uruguayen", "symbol": "UYU"},
    "UZS": {"name": "Soum ouzbek", "symbol": "UZS"},
    "VES": {"name": "Bolivar", "symbol": "VES"},
    "VND": {"name": "Dong", "symbol": "VND"},
    "VUV": {"name": "Vatu", "symbol": "VUV"},
    "WST": {"name": "Tala", "symbol": "WST"},
    "XAF": {"name": "Franc CFA", "symbol": "FCFA"},
    "XCD": {"name": "Dollar des Caraibes orientales", "symbol": "EC$"},
    "XOF": {"name": "Franc CFA BCEAO", "symbol": "CFA"},
    "YER": {"name": "Rial yemenite", "symbol": "YER"},
    "ZAR": {"name": "Rand", "symbol": "ZAR"},
    "ZMW": {"name": "Kwacha zambien", "symbol": "ZMW"},
    "ZWG": {"name": "Zimbabwe Gold", "symbol": "ZWG"},
}


def get_country_choices():
    return [(country_name, country_name) for _, country_name, _ in WORLD_COUNTRIES]


def get_currency_choices():
    codes = sorted({currency_code for _, _, currency_code in WORLD_COUNTRIES})
    return [(code, f"{code} / {get_currency_name(code)}") for code in codes]


def build_country_currency_map():
    return {country_name: currency_code for _, country_name, currency_code in WORLD_COUNTRIES}


def get_default_currency_for_country(country_name, default="CDF"):
    return build_country_currency_map().get((country_name or "").strip(), default)


def get_currency_name(currency_code):
    return CURRENCY_DETAILS.get(currency_code or "", {}).get("name", currency_code or "Devise")


def get_currency_symbol(currency_code):
    return CURRENCY_DETAILS.get(currency_code or "", {}).get("symbol", currency_code or "")
