# Generated by Django 6.0.6 on 2026-06-26 16:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joatham_rh', '0003_employe_user'),
        ('joatham_users', '0020_useractivesession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvanceSalaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_avance', models.DateField(default=django.utils.timezone.localdate)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('motif', models.TextField(blank=True, default='')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('annulee', 'Annulée')], default='validee', max_length=20)),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('mobile_money', 'Mobile Money'), ('virement', 'Virement'), ('autre', 'Autre')], default='especes', max_length=20)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rh_avances_salaire_creees', to=settings.AUTH_USER_MODEL)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances_salaire', to='joatham_rh.employe')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rh_avances_salaire', to='joatham_users.entreprise')),
            ],
            options={
                'ordering': ['-date_avance', '-created_at', '-id'],
                'indexes': [models.Index(fields=['entreprise', 'date_avance'], name='rh_avance_ent_date_idx'), models.Index(fields=['entreprise', 'statut', 'date_avance'], name='rh_avance_ent_statut_dt_idx'), models.Index(fields=['employe', 'date_avance'], name='rh_avance_emp_date_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('montant__gt', 0)), name='rh_avance_salaire_montant_gt_zero')],
            },
        ),
        migrations.CreateModel(
            name='PaiementSalaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode_mois', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('periode_annee', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000)])),
                ('salaire_base', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_avances_deduites', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('primes', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('retenues', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('montant_net_a_payer', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('montant_paye', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('statut', models.CharField(choices=[('non_paye', 'Non payé'), ('partiel', 'Partiel'), ('paye', 'Payé')], default='non_paye', max_length=20)),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('mobile_money', 'Mobile Money'), ('virement', 'Virement'), ('autre', 'Autre')], default='especes', max_length=20)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rh_paiements_salaire_crees', to=settings.AUTH_USER_MODEL)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_salaire', to='joatham_rh.employe')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rh_paiements_salaire', to='joatham_users.entreprise')),
            ],
            options={
                'ordering': ['-periode_annee', '-periode_mois', 'employe__nom', '-created_at', '-id'],
                'indexes': [models.Index(fields=['entreprise', 'periode_annee', 'periode_mois'], name='rh_paie_ent_period_idx'), models.Index(fields=['entreprise', 'statut'], name='rh_paie_ent_statut_idx'), models.Index(fields=['employe', 'periode_annee', 'periode_mois'], name='rh_paie_emp_period_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('periode_mois__gte', 1), ('periode_mois__lte', 12)), name='rh_paie_mois_valid'), models.CheckConstraint(condition=models.Q(('salaire_base__gte', 0)), name='rh_paie_salaire_base_gte_zero'), models.CheckConstraint(condition=models.Q(('total_avances_deduites__gte', 0)), name='rh_paie_avances_gte_zero'), models.CheckConstraint(condition=models.Q(('primes__gte', 0)), name='rh_paie_primes_gte_zero'), models.CheckConstraint(condition=models.Q(('retenues__gte', 0)), name='rh_paie_retenues_gte_zero'), models.CheckConstraint(condition=models.Q(('montant_net_a_payer__gte', 0)), name='rh_paie_net_gte_zero'), models.CheckConstraint(condition=models.Q(('montant_paye__gte', 0)), name='rh_paie_montant_paye_gte_zero')],
            },
        ),
    ]
