# Generated by Django 6.0.6 on 2026-06-26 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joatham_caisse', '0003_mouvementcaisse_moyen_paiement'),
        ('joatham_rh', '0004_avancesalaire_paiementsalaire'),
        ('joatham_users', '0020_useractivesession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementsalaire',
            name='caisse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rh_paiements_salaire', to='joatham_caisse.caisse'),
        ),
        migrations.AddField(
            model_name='paiementsalaire',
            name='mouvement_caisse',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rh_paiement_salaire', to='joatham_caisse.mouvementcaisse'),
        ),
        migrations.AddField(
            model_name='paiementsalaire',
            name='session_caisse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rh_paiements_salaire', to='joatham_caisse.sessioncaisse'),
        ),
        migrations.AddIndex(
            model_name='paiementsalaire',
            index=models.Index(fields=['caisse', 'session_caisse'], name='rh_paie_cash_session_idx'),
        ),
    ]
