# Generated by Django 6.0.3 on 2026-04-19 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joatham_depenses', '0001_initial'),
        ('joatham_users', '0006_subscription_v1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depense',
            name='entreprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='joatham_users.entreprise'),
        ),
    ]
