# Generated by Codex on 2026-04-18

import datetime
import django.db.models.deletion
from django.db import migrations, models


def bootstrap_existing_entreprises(apps, schema_editor):
    Entreprise = apps.get_model("joatham_users", "Entreprise")
    ExerciceComptable = apps.get_model("joatham_comptabilite", "ExerciceComptable")
    CompteComptable = apps.get_model("joatham_comptabilite", "CompteComptable")
    JournalComptable = apps.get_model("joatham_comptabilite", "JournalComptable")

    today = datetime.date.today()
    exercices = {
        "code": f"EX-{today.year}",
        "date_debut": datetime.date(today.year, 1, 1),
        "date_fin": datetime.date(today.year, 12, 31),
        "statut": "ouvert",
    }

    comptes = [
        {"numero": "101", "nom": "Capital", "classe": "1", "categorie": "capitaux_propres", "sens_normal": "credit", "actif": True},
        {"numero": "411", "nom": "Clients", "classe": "4", "categorie": "tiers", "sens_normal": "debit", "actif": True},
        {"numero": "401", "nom": "Fournisseurs", "classe": "4", "categorie": "tiers", "sens_normal": "credit", "actif": True},
        {"numero": "443", "nom": "TVA collectee", "classe": "4", "categorie": "fiscal", "sens_normal": "credit", "actif": True},
        {"numero": "444", "nom": "TVA deductibile", "classe": "4", "categorie": "fiscal", "sens_normal": "debit", "actif": True},
        {"numero": "521", "nom": "Banque", "classe": "5", "categorie": "tresorerie", "sens_normal": "debit", "actif": True},
        {"numero": "531", "nom": "Caisse", "classe": "5", "categorie": "tresorerie", "sens_normal": "debit", "actif": True},
        {"numero": "601", "nom": "Charges d'exploitation", "classe": "6", "categorie": "charge", "sens_normal": "debit", "actif": True},
        {"numero": "701", "nom": "Ventes", "classe": "7", "categorie": "produit", "sens_normal": "credit", "actif": True},
    ]

    journaux = [
        {"code": "JV", "nom": "Journal des ventes", "type_journal": "ventes", "actif": True},
        {"code": "JA", "nom": "Journal des achats", "type_journal": "achats", "actif": True},
        {"code": "TR", "nom": "Journal de tresorerie", "type_journal": "tresorerie", "actif": True},
        {"code": "OD", "nom": "Operations diverses", "type_journal": "od", "actif": True},
    ]

    for entreprise in Entreprise.objects.all():
        ExerciceComptable.objects.get_or_create(entreprise=entreprise, code=exercices["code"], defaults=exercices)
        for compte in comptes:
            CompteComptable.objects.get_or_create(entreprise=entreprise, numero=compte["numero"], defaults=compte)
        for journal in journaux:
            JournalComptable.objects.get_or_create(entreprise=entreprise, code=journal["code"], defaults=journal)


class Migration(migrations.Migration):

    dependencies = [
        ("joatham_comptabilite", "0001_initial"),
        ("joatham_users", "0004_entreprise_billing_fields"),
    ]

    operations = [
        migrations.DeleteModel(name="Ecriture"),
        migrations.DeleteModel(name="Mouvement"),
        migrations.DeleteModel(name="Journal"),
        migrations.DeleteModel(name="Compte"),
        migrations.CreateModel(
            name="ExerciceComptable",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=20)),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                ("statut", models.CharField(choices=[("ouvert", "Ouvert"), ("ferme", "Ferme")], default="ouvert", max_length=20)),
                ("entreprise", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="exercices_comptables", to="joatham_users.entreprise")),
            ],
            options={"ordering": ["-date_debut"]},
        ),
        migrations.CreateModel(
            name="CompteComptable",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("numero", models.CharField(max_length=20)),
                ("nom", models.CharField(max_length=120)),
                ("classe", models.CharField(max_length=2)),
                ("categorie", models.CharField(max_length=30)),
                ("sens_normal", models.CharField(choices=[("debit", "Debit"), ("credit", "Credit")], max_length=10)),
                ("actif", models.BooleanField(default=True)),
                ("entreprise", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="comptes_comptables", to="joatham_users.entreprise")),
            ],
            options={"ordering": ["numero"]},
        ),
        migrations.CreateModel(
            name="JournalComptable",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=20)),
                ("nom", models.CharField(max_length=120)),
                ("type_journal", models.CharField(choices=[("ventes", "Ventes"), ("achats", "Achats"), ("tresorerie", "Tresorerie"), ("od", "Operations diverses")], max_length=20)),
                ("actif", models.BooleanField(default=True)),
                ("entreprise", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="journaux_comptables", to="joatham_users.entreprise")),
            ],
            options={"ordering": ["code"]},
        ),
        migrations.CreateModel(
            name="EcritureComptable",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("numero_piece", models.CharField(max_length=50)),
                ("date_piece", models.DateField()),
                ("libelle", models.CharField(max_length=255)),
                ("statut", models.CharField(choices=[("brouillon", "Brouillon"), ("valide", "Valide"), ("annulee", "Annulee")], default="valide", max_length=20)),
                ("source_app", models.CharField(blank=True, default="", max_length=50)),
                ("source_model", models.CharField(blank=True, default="", max_length=50)),
                ("source_id", models.PositiveIntegerField(blank=True, null=True)),
                ("source_event", models.CharField(blank=True, default="", max_length=50)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("entreprise", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ecritures_comptables", to="joatham_users.entreprise")),
                ("exercice", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="ecritures", to="joatham_comptabilite.exercicecomptable")),
                ("journal", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="ecritures", to="joatham_comptabilite.journalcomptable")),
            ],
            options={"ordering": ["-date_piece", "-id"]},
        ),
        migrations.CreateModel(
            name="LigneEcritureComptable",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("libelle", models.CharField(blank=True, default="", max_length=255)),
                ("debit", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("credit", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("compte", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="lignes_ecriture", to="joatham_comptabilite.comptecomptable")),
                ("ecriture", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lignes", to="joatham_comptabilite.ecriturecomptable")),
            ],
            options={"ordering": ["id"]},
        ),
        migrations.AddConstraint(
            model_name="exercicecomptable",
            constraint=models.UniqueConstraint(fields=("entreprise", "code"), name="uniq_exercice_code_entreprise"),
        ),
        migrations.AddConstraint(
            model_name="comptecomptable",
            constraint=models.UniqueConstraint(fields=("entreprise", "numero"), name="uniq_compte_numero_entreprise"),
        ),
        migrations.AddConstraint(
            model_name="journalcomptable",
            constraint=models.UniqueConstraint(fields=("entreprise", "code"), name="uniq_journal_code_entreprise"),
        ),
        migrations.AddIndex(
            model_name="ecriturecomptable",
            index=models.Index(fields=["entreprise", "date_piece"], name="joatham_com_entrepr_53fb85_idx"),
        ),
        migrations.AddIndex(
            model_name="ecriturecomptable",
            index=models.Index(fields=["entreprise", "source_app", "source_model", "source_id"], name="joatham_com_entrepr_1feab4_idx"),
        ),
        migrations.AddConstraint(
            model_name="ecriturecomptable",
            constraint=models.UniqueConstraint(
                condition=models.Q(source_app__gt="", source_model__gt="", source_event__gt="", source_id__isnull=False),
                fields=("entreprise", "source_app", "source_model", "source_id", "source_event"),
                name="uniq_ecriture_source_event_entreprise",
            ),
        ),
        migrations.RunPython(bootstrap_existing_entreprises, migrations.RunPython.noop),
    ]
