# Generated by Django 6.0.3 on 2026-04-19 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joatham_comptabilite', '0002_refactor_comptabilite_core'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ecriturecomptable',
            new_name='joatham_com_entrepr_e95e6c_idx',
            old_name='joatham_com_entrepr_53fb85_idx',
        ),
        migrations.RenameIndex(
            model_name='ecriturecomptable',
            new_name='joatham_com_entrepr_e3c0a1_idx',
            old_name='joatham_com_entrepr_1feab4_idx',
        ),
    ]
