# Generated by Django 6.0.3 on 2026-04-10 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joatham_users', '0002_entreprise_user_entreprise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prix', models.FloatField()),
                ('duree_jours', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='entreprise',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='entreprise',
            name='email',
        ),
        migrations.RemoveField(
            model_name='entreprise',
            name='telephone',
        ),
        migrations.AddField(
            model_name='entreprise',
            name='date_expiration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='abonnement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='joatham_users.abonnement'),
        ),
    ]
