# Generated by Codex on 2026-04-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("joatham_users", "0003_abonnement_remove_entreprise_adresse_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entreprise",
            name="adresse",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="banque",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="compte_bancaire",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="id_nat",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="numero_impot",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="pays",
            field=models.CharField(blank=True, default="RDC", max_length=100),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="raison_sociale",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="rccm",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="telephone",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="ville",
            field=models.CharField(blank=True, default="Matadi", max_length=100),
        ),
    ]
