# Generated by Django 6.0.3 on 2026-04-18

from django.db import migrations, models


def migrate_admin_role_to_proprietaire(apps, schema_editor):
    User = apps.get_model("joatham_users", "User")
    User.objects.filter(role="admin").update(role="proprietaire")


class Migration(migrations.Migration):

    dependencies = [
        ("joatham_users", "0004_entreprise_billing_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("proprietaire", "Proprietaire"),
                    ("gestionnaire", "Gestionnaire"),
                    ("comptable", "Comptable"),
                ],
                max_length=20,
            ),
        ),
        migrations.RunPython(migrate_admin_role_to_proprietaire, migrations.RunPython.noop),
    ]
