# Generated by Django 6.0.3 on 2026-04-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joatham_users', '0010_user_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='referentiel_comptable',
            field=models.CharField(choices=[('syscohada', 'SYSCOHADA'), ('pcg', 'PCG'), ('ifrs_simplifie', 'IFRS simplifie'), ('autre', 'Autre')], default='syscohada', max_length=30),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='taux_tva_defaut',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
