# Generated by Django 6.0.3 on 2026-04-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joatham_users', '0011_entreprise_referentiel_comptable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super admin'), ('proprietaire', 'Proprietaire'), ('gestionnaire', 'Gestionnaire'), ('comptable', 'Comptable')], max_length=20),
        ),
    ]
