# Generated by Django 6.0.3 on 2026-04-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joatham_users', '0012_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
