# Generated by Codex on 2026-05-02

from django.db import migrations, models
import django.utils.timezone
import joatham_users.models


class Migration(migrations.Migration):

    dependencies = [
        ("joatham_users", "0016_user_preferred_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntrepriseInvitation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("full_name", models.CharField(blank=True, default="", max_length=150)),
                ("token", models.CharField(default=joatham_users.models.generate_invitation_token, max_length=128, unique=True)),
                ("is_used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField(default=joatham_users.models.default_invitation_expiry)),
                ("source", models.CharField(blank=True, db_index=True, default="question_publique", max_length=80)),
                ("last_reminder_sent_at", models.DateTimeField(blank=True, null=True)),
                ("reminder_count", models.PositiveSmallIntegerField(default=0)),
                ("max_reminders", models.PositiveSmallIntegerField(default=2)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["is_used", "expires_at", "created_at"], name="joatham_use_is_used_3d8595_idx"),
                    models.Index(fields=["reminder_count", "last_reminder_sent_at"], name="joatham_use_reminde_7b9e9d_idx"),
                ],
            },
        ),
    ]
