# Generated by Django 6.0.3 on 2026-05-02 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joatham_users', '0017_entrepriseinvitation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='entrepriseinvitation',
            new_name='joatham_use_is_used_97b7ab_idx',
            old_name='joatham_use_is_used_3d8595_idx',
        ),
        migrations.RenameIndex(
            model_name='entrepriseinvitation',
            new_name='joatham_use_reminde_704aab_idx',
            old_name='joatham_use_reminde_7b9e9d_idx',
        ),
    ]
