# Generated by Codex on 2026-04-17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("joatham_clients", "__first__"),
        ("joatham_users", "0004_entreprise_billing_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Facture",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("client_nom", models.CharField(blank=True, max_length=100, null=True)),
                ("numero", models.CharField(editable=False, max_length=20)),
                ("numero_sequence", models.PositiveIntegerField(editable=False)),
                ("montant", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("description", models.TextField(blank=True, default="")),
                ("tva", models.IntegerField(choices=[(0, "Exonere (0%)"), (1, "TVA 1%"), (5, "TVA 5%"), (16, "TVA 16%")], default=16)),
                ("remise", models.FloatField(default=0)),
                ("rabais", models.FloatField(default=0)),
                ("ristourne", models.FloatField(default=0)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("paye", models.BooleanField(default=False)),
                ("client", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="joatham_clients.client")),
                ("entreprise", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="factures", to="joatham_users.entreprise")),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="FactureSequence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("dernier_numero", models.PositiveIntegerField(default=0)),
                ("entreprise", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="facture_sequence", to="joatham_users.entreprise")),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nom", models.CharField(max_length=100)),
                ("prix", models.DecimalField(decimal_places=2, max_digits=10)),
                ("numero", models.CharField(blank=True, max_length=20, null=True)),
                ("entreprise", models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="joatham_users.entreprise")),
            ],
        ),
        migrations.CreateModel(
            name="LigneFacture",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("designation", models.CharField(max_length=200)),
                ("quantite", models.IntegerField(default=1)),
                ("prix_unitaire", models.DecimalField(decimal_places=2, max_digits=10)),
                ("facture", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lignes", to="joatham_billing.facture")),
            ],
        ),
        migrations.AddConstraint(
            model_name="facture",
            constraint=models.UniqueConstraint(fields=("entreprise", "numero"), name="uniq_facture_numero_par_entreprise"),
        ),
        migrations.AddConstraint(
            model_name="facture",
            constraint=models.UniqueConstraint(fields=("entreprise", "numero_sequence"), name="uniq_facture_sequence_par_entreprise"),
        ),
    ]
