# Generated by Codex on 2026-04-17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("joatham_billing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="facture",
            name="statut",
            field=models.CharField(
                choices=[
                    ("brouillon", "Brouillon"),
                    ("emise", "Emise"),
                    ("payee", "Payee"),
                    ("annulee", "Annulee"),
                ],
                default="brouillon",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="FactureHistorique",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(choices=[("creation", "Creation"), ("modification", "Modification"), ("statut", "Changement de statut"), ("paiement", "Paiement"), ("pdf", "Generation PDF")], max_length=20)),
                ("description", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("entreprise", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="historique_factures", to="joatham_users.entreprise")),
                ("facture", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="historique", to="joatham_billing.facture")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="actions_factures", to="joatham_users.user")),
            ],
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.CreateModel(
            name="PaiementFacture",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                ("mode", models.CharField(choices=[("especes", "Especes"), ("virement", "Virement"), ("mobile_money", "Mobile Money"), ("cheque", "Cheque"), ("autre", "Autre")], default="especes", max_length=20)),
                ("reference", models.CharField(blank=True, default="", max_length=100)),
                ("date_paiement", models.DateTimeField(default=django.utils.timezone.now)),
                ("statut", models.CharField(choices=[("en_attente", "En attente"), ("valide", "Valide"), ("annule", "Annule")], default="valide", max_length=20)),
                ("note", models.TextField(blank=True, default="")),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("entreprise", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="paiements_factures", to="joatham_users.entreprise")),
                ("facture", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="paiements", to="joatham_billing.facture")),
            ],
            options={"ordering": ["-date_paiement", "-id"]},
        ),
    ]
