# Generated by Django 6.0.3 on 2026-04-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joatham_billing', '0002_facture_workflow_and_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='tva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
