# Generated by Django 6.0.3 on 2026-04-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joatham_billing', '0006_lignefacture_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='stock_applique',
            field=models.BooleanField(default=False),
        ),
    ]
