# Generated by Django 6.0.3 on 2026-05-08 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("joatham_billing", "0007_facture_stock_applique"),
        ("joatham_caisse", "0002_rename_cash_move_company_type_date_idx_cash_mov_ent_type_dt_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paiementfacture",
            name="caisse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="paiements_factures",
                to="joatham_caisse.caisse",
            ),
        ),
        migrations.AddField(
            model_name="paiementfacture",
            name="session_caisse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="paiements_factures",
                to="joatham_caisse.sessioncaisse",
            ),
        ),
    ]
