# Generated by Django 6.0.3 on 2026-05-08 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joatham_caisse', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mouvementcaisse',
            new_name='cash_mov_ent_type_dt_idx',
            old_name='cash_move_company_type_date_idx',
        ),
        migrations.RenameIndex(
            model_name='sessioncaisse',
            new_name='cash_sess_ent_stat_idx',
            old_name='cash_session_company_status_idx',
        ),
        migrations.RenameIndex(
            model_name='sessioncaisse',
            new_name='cash_sess_caisse_stat_idx',
            old_name='cash_session_cashbox_status_idx',
        ),
        migrations.RenameIndex(
            model_name='validationcaisse',
            new_name='cash_val_ent_dt_idx',
            old_name='cash_validation_company_date_idx',
        ),
        migrations.RenameIndex(
            model_name='validationcaisse',
            new_name='cash_val_sess_dec_idx',
            old_name='cash_validation_session_decision_idx',
        ),
    ]
